const countryCodes = [
    { code: "+91", country: "India", iso: "in", minLength: 10, maxLength: 10 },
    { code: "+1", country: "USA / Canada", iso: "us", minLength: 10, maxLength: 10 },
    { code: "+44", country: "United Kingdom", iso: "gb", minLength: 10, maxLength: 10 },
    { code: "+61", country: "Australia", iso: "au", minLength: 9, maxLength: 9 },
    { code: "+971", country: "UAE", iso: "ae", minLength: 9, maxLength: 9 },
    { code: "+966", country: "Saudi Arabia", iso: "sa", minLength: 9, maxLength: 9 },
    { code: "+65", country: "Singapore", iso: "sg", minLength: 8, maxLength: 8 },
    { code: "+60", country: "Malaysia", iso: "my", minLength: 9, maxLength: 10 },
    { code: "+49", country: "Germany", iso: "de", minLength: 10, maxLength: 11 },
    { code: "+33", country: "France", iso: "fr", minLength: 9, maxLength: 9 },
    { code: "+39", country: "Italy", iso: "it", minLength: 9, maxLength: 10 },
    { code: "+34", country: "Spain", iso: "es", minLength: 9, maxLength: 9 },
    { code: "+31", country: "Netherlands", iso: "nl", minLength: 9, maxLength: 9 },
    { code: "+7", country: "Russia", iso: "ru", minLength: 10, maxLength: 10 },
    { code: "+86", country: "China", iso: "cn", minLength: 11, maxLength: 11 },
    { code: "+81", country: "Japan", iso: "jp", minLength: 10, maxLength: 10 },
    { code: "+82", country: "South Korea", iso: "kr", minLength: 10, maxLength: 10 },
    { code: "+55", country: "Brazil", iso: "br", minLength: 10, maxLength: 11 },
    { code: "+52", country: "Mexico", iso: "mx", minLength: 10, maxLength: 10 },
    { code: "+27", country: "South Africa", iso: "za", minLength: 9, maxLength: 9 },
    { code: "+92", country: "Pakistan", iso: "pk", minLength: 10, maxLength: 10 },
    { code: "+880", country: "Bangladesh", iso: "bd", minLength: 10, maxLength: 10 },
    { code: "+94", country: "Sri Lanka", iso: "lk", minLength: 9, maxLength: 9 },
    { code: "+977", country: "Nepal", iso: "np", minLength: 10, maxLength: 10 },
    { code: "+64", country: "New Zealand", iso: "nz", minLength: 8, maxLength: 9 },
    { code: "+353", country: "Ireland", iso: "ie", minLength: 9, maxLength: 9 },
    { code: "+41", country: "Switzerland", iso: "ch", minLength: 9, maxLength: 9 },
    { code: "+46", country: "Sweden", iso: "se", minLength: 9, maxLength: 9 },
    { code: "+47", country: "Norway", iso: "no", minLength: 8, maxLength: 8 },
    { code: "+45", country: "Denmark", iso: "dk", minLength: 8, maxLength: 8 },
    { code: "+358", country: "Finland", iso: "fi", minLength: 9, maxLength: 10 },
    { code: "+48", country: "Poland", iso: "pl", minLength: 9, maxLength: 9 },
    { code: "+90", country: "Turkey", iso: "tr", minLength: 10, maxLength: 10 },
    { code: "+20", country: "Egypt", iso: "eg", minLength: 10, maxLength: 10 },
    { code: "+234", country: "Nigeria", iso: "ng", minLength: 10, maxLength: 10 },
    { code: "+254", country: "Kenya", iso: "ke", minLength: 9, maxLength: 9 },
    { code: "+62", country: "Indonesia", iso: "id", minLength: 9, maxLength: 12 },
    { code: "+63", country: "Philippines", iso: "ph", minLength: 10, maxLength: 10 },
    { code: "+66", country: "Thailand", iso: "th", minLength: 9, maxLength: 9 },
    { code: "+84", country: "Vietnam", iso: "vn", minLength: 9, maxLength: 10 },
];

export default countryCodes;