// Shared specializations list used across all components
const specializations = [
    "Allergist",
    "Anesthesiologist",
    "Cardiologist",
    "Dentist",
    "Dermatologist",
    "Dietitian",
    "Emergency Medicine",
    "Endocrinologist",
    "ENT Specialist",
    "Family Medicine",
    "Gastroenterologist",
    "General Physician",
    "Geriatrics",
    "Gynecologist",
    "Hematologist",
    "Immunologist",
    "Infectious Disease",
    "Internal Medicine",
    "Neonatologist",
    "Nephrologist",
    "Neurologist",
    "Neurosurgeon",
    "Oncologist",
    "Ophthalmologist",
    "Orthopedic Surgeon",
    "Pediatrician",
    "Physiotherapist",
    "Plastic Surgeon",
    "Psychiatrist",
    "Pulmonologist",
    "Radiologist",
    "Reproductive Medicine",
    "Rheumatologist",
    "Spine Surgeon",
    "Sports Medicine",
    "Surgeon",
    "Urologist",
    "Vascular Surgeon",
];

export default specializations;